import os
import json
import shutil
import subprocess

TEMPLATES = {
    "package.json": lambda name: json.dumps({
        "name": name,
        "version": "0.1.0",
        "private": True,
        "scripts": {
            "dev": "next dev",
            "build": "next build",
            "start": "next start",
            "lint": "next lint"
        },
        "dependencies": {
            "next": "^15.0.0",
            "react": "^19.0.0",
            "react-dom": "^19.0.0"
        },
        "devDependencies": {
            "eslint": "^9",
            "eslint-config-next": "^15.0.0"
        }
    }, indent=2),

    "next.config.js": lambda name: "/** @type {import('next').NextConfig} */\nconst nextConfig = {}\nmodule.exports = nextConfig\n",

    "src/app/layout.js": lambda name: f"""export const metadata = {{
  title: {{
    default: '{name} — Professional Platform',
    template: '%s | {name}'
  }},
  description: 'A high-performance web application scaffolded with industry-standard SEO, PWA, and security best practices.',
  keywords: 'web app, nextjs, react, professional, seo optimized, pwa, fast loading',
  robots: {{
    index: true,
    follow: true,
    googleBot: {{
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    }},
  }},
}}

export default function RootLayout({{ children }}) {{
  return (
    <html lang="en">
      <body>{{children}}</body>
    </html>
  )
}}
""",

    "src/app/page.js": lambda name: f"""import SchemaMarkup from './components/SchemaMarkup';

export default function Home() {{
  const websiteSchema = {{
    "@context": "https://schema.org",
    "@type": "WebSite",
    "name": "{name}",
    "url": "https://example.com",
    "description": "A high-performance web application scaffolded with industry-standard SEO and PWA best practices."
  }};

  return (
    <>
      <SchemaMarkup schemaData={{websiteSchema}} />
      <header style={{{{ padding: '2rem', borderBottom: '1px solid #eaeaea' }}}}>
        <nav style={{{{ maxWidth: '1200px', margin: '0 auto', display: 'flex', justifyContent: 'space-between' }}}}>
          <strong>{name}</strong>
          <div>
            <a href="#about" style={{{{ marginRight: '1rem' }}}}>About</a>
            <a href="#features">Features</a>
          </div>
        </nav>
      </header>
      
      <main style={{{{ maxWidth: '1200px', margin: '0 auto', padding: '4rem 2rem' }}}}>
        <section id="about" style={{{{ marginBottom: '4rem' }}}}>
          <h1 style={{{{ fontSize: '3rem', marginBottom: '1.5rem' }}}}>Welcome to {name}</h1>
          <p style={{{{ fontSize: '1.25rem', lineHeight: '1.6', color: '#666' }}}}>
            This project was scaffolded with premium SEO structures, semantic HTML5 tags, and dynamic sitemaps.
          </p>
        </section>
        
        <section id="features" style={{{{ padding: '2rem 0' }}}}>
          <h2>Built-in DevOps & SEO Best Practices</h2>
          <ul style={{{{ lineHeight: '2', fontSize: '1.1rem' }}}}>
            <li><strong>JSON-LD Schema Markup</strong> (ready for Google rich results)</li>
            <li><strong>Dynamic Next.js Sitemaps</strong> (auto-generated at /sitemap.xml)</li>
            <li><strong>Fully Compliant robots.txt</strong> (controlling search crawler indexation)</li>
            <li><strong>Semantic Layouts</strong> (structuring header, main, and footer elements)</li>
          </ul>
        </section>
      </main>

      <footer style={{{{ borderTop: '1px solid #eaeaea', padding: '2rem', textAlign: 'center', color: '#888' }}}}>
        <p>&copy; {{new Date().getFullYear()}} {name}. All rights reserved.</p>
      </footer>
    </>
  )
}}
""",

    "src/app/components/SchemaMarkup.jsx": lambda name: """import Script from 'next/script';

export default function SchemaMarkup({ schemaData }) {
  return (
    <Script
      id="json-ld-schema"
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaData) }}
    />
  );
}
""",

    "src/app/sitemap.js": lambda name: """export default function sitemap() {
  return [
    {
      url: 'https://example.com',
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 1.0,
    }
  ];
}
""",

    "public/robots.txt": lambda name: """User-agent: *
Allow: /
Disallow: /api/

Sitemap: https://example.com/sitemap.xml
""",

    ".gitignore": lambda name: "node_modules/\n.next/\nout/\n.env\n.env.local\n",

    "README.md": lambda name: f"# {name}\n\nGenerated by DevOps Concierge Agent with built-in premium SEO architecture.\n\n## Getting Started\n\n```bash\nnpm install\nnpm run dev\n```\n",
}


def fast_dir_copy(src, dst):
    import platform
    # If Windows, use robocopy for 10x faster multi-threaded copy!
    if platform.system() == "Windows":
        try:
            # robocopy <src> <dst> /E /MT:32 (multi-threaded, 32 threads)
            # /NFL /NDL /NJH /NJS /nc /ns /np suppresses output logs for maximum speed
            proc = subprocess.run(
                ["robocopy", src, dst, "/E", "/MT:32", "/NFL", "/NDL", "/NJH", "/NJS", "/nc", "/ns", "/np"],
                shell=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL
            )
            # Robocopy exit codes < 8 mean success
            if proc.returncode < 8:
                return True
        except Exception:
            pass
            
    # Fallback to shutil.copytree
    shutil.copytree(src, dst, symlinks=True)
    return True


def ensure_and_copy_cache(output_dir):
    backend_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    cache_dir = os.path.join(backend_dir, "cache", "nextjs_cache")
    cache_node_modules = os.path.join(cache_dir, "node_modules")
    
    # 1. If cache doesn't exist, create it once
    if not os.path.exists(cache_node_modules):
        os.makedirs(cache_dir, exist_ok=True)
        # Write standard package.json
        pkg_data = TEMPLATES["package.json"]("cache-temp")
        with open(os.path.join(cache_dir, "package.json"), "w", encoding="utf-8") as f:
            f.write(pkg_data)
        
        # Run npm/pnpm install to populate the cache
        pkg_manager = "npm"
        if shutil.which("pnpm"):
            pkg_manager = "pnpm"
        elif shutil.which("bun"):
            pkg_manager = "bun"
            
        print(f"[Scaffolder Cache] Populating node_modules cache using {pkg_manager}...")
        try:
            # We run it synchronously as a one-time setup
            subprocess.run(
                f"{pkg_manager} install", 
                shell=True, 
                cwd=cache_dir, 
                stdout=subprocess.DEVNULL, 
                stderr=subprocess.DEVNULL,
                timeout=120
            )
        except Exception as e:
            print(f"[Scaffolder Cache] Failed to populate cache: {e}")
            
    # 2. If the cache is successfully populated, copy it to the target directory!
    if os.path.exists(cache_node_modules):
        target_node_modules = os.path.join(output_dir, "node_modules")
        if not os.path.exists(target_node_modules):
            print(f"[Scaffolder Cache] Instantly copying cached node_modules to {output_dir}...")
            try:
                # Use high-speed multi-threaded directory copying
                fast_dir_copy(cache_node_modules, target_node_modules)
                print("[Scaffolder Cache] Copy completed successfully!")
            except Exception as e:
                print(f"[Scaffolder Cache] Copy failed: {e}")


def scaffold_nextjs(project_name, output_dir=None):
    if not output_dir:
        base = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "generated_projects")
        output_dir = os.path.join(base, project_name)

    os.makedirs(output_dir, exist_ok=True)
    created_files = []

    for rel_path, generator in TEMPLATES.items():
        full_path = os.path.join(output_dir, rel_path)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(generator(project_name))
        created_files.append(rel_path)

    # Automatically seed the project with pre-installed node_modules!
    ensure_and_copy_cache(output_dir)

    return {
        "success": True,
        "project_name": project_name,
        "output_dir": output_dir,
        "files_created": created_files
    }


def add_file_to_project(project_dir, file_path, content):
    full_path = os.path.join(project_dir, file_path)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    with open(full_path, "w", encoding="utf-8") as f:
        f.write(content)
    return {"success": True, "file": file_path}
